nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'X-User-Id', 'X-Total-Count', 'X-Per-Page']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': null
