name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup prod dependencies
        run: composer install --no-dev --no-scripts
      - name: Warmup cache
        run: php bin/console cache:warmup --env=prod
      - name: Add serverless
        run: yarn global add serverless@3
      - name: Deploy
        run: sls deploy --stage prod --verbose
        env:
          AWS_REGION: eu-central-1
          VPC_IP_DIGIT: '15'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          APP_DOMAIN_HOSTED_ZONE: ${{ secrets.APP_DOMAIN_HOSTED_ZONE }}
          APP_DOMAIN: api.baby-journal.app
      - name: Migrations
        run: sls bref:cli --stage prod --args="doc:mig:mig -n"
        env:
          AWS_REGION: eu-central-1
          VPC_IP_DIGIT: '15'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          APP_DOMAIN_HOSTED_ZONE: ${{ secrets.APP_DOMAIN_HOSTED_ZONE }}
          APP_DOMAIN: api.baby-journal.app
