on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup prod dependencies
        run: composer install --no-dev --no-scripts
      - name: Warmup cache
        run: php bin/console cache:warmup --env=prod
      - name: Deploy
        uses: serverless/github-action@v3
        with:
          args: deploy --stage prod --verbose
        env:
          AWS_REGION: eu-central-1
          VPC_IP_DIGIT: '15'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
